// 手写类似pubsub-js的事件队列库/webpack/src/react/components/Demo03Com.jsx
import React, { memo } from 'react'
import { Button } from 'antd'
import pubsub from '../../pubsub'

const Demo01Com = memo(() => {
  const addA = () => pubsub.publish('react-addA')
  const addB = () => pubsub.publish('react-addB')

  return (
    <div className="demo">
      <h2>demo03组件</h2>
      <Button onClick={() => addA()}>a++</Button>
      <Button onClick={addB}>b++</Button>
    </div>
  )
})

export default Demo01Com

// 手写类似pubsub-js的事件队列库/vite/src/vue/components/Demo03Com.vue
<template>
  <div class="demo">
    <h2>demo03组件</h2>
    <el-button @click="addA">a++</el-button>
    <el-button @click="addB">b++</el-button>
  </div>
</template>

<script lang="ts" setup>
import pubsub from '../../pubsub'

const addA = () => pubsub.publish('vue-addA')
const addB = () => pubsub.publish('vue-addB')
</script>

<style scoped lang="less"></style>
