// 手写类似pubsub-js的事件队列库/vite/src/react/components/Demo01Com.tsx
import React, { memo, useEffect, useState } from 'react'
import { Button, Space } from 'antd'
import pubsub from '../../pubsub'

interface PropsTypes {
  count: number
  addCount: () => void
}

const Demo01Com: React.FC<PropsTypes> = memo(({ count, addCount }) => {
  const [a, setA] = useState<number>(6)
  const [b, setB] = useState<number>(10)

  const addA = () => setA(a + 1)
  const addB = () => setB(b + 1)

  pubsub.subscribe('react-addA', addA)
  pubsub.subscribe('react-addB', addB)

  useEffect(() => {
    console.log('组件挂载了')

    return () => {
      console.log('组件卸载了 清除订阅')
      pubsub.unsubscribe('react')
    }
  }, [])

  return (
    <div className="demo">
      <h2>demo01组件</h2>
      <h3>
        count：{count} a： {a} b：{b}
      </h3>
      <Space>
        <Button onClick={addCount}>改变app组件count的值</Button>
        <Button onClick={addA}>a++</Button>
        <Button onClick={addB}>b++</Button>
      </Space>
    </div>
  )
})

export default Demo01Com

// 手写类似pubsub-js的事件队列库/vite/src/vue/components/Demo01Com.vue
<template>
  <div class="demo">
    <h2>demo01组件</h2>
    <h3>count：{{ count }} a： {{ a }} b：{{ b }}</h3>
    <el-button @click="addCount">改变app组件count值</el-button>
    <el-button @click="addA">a++</el-button>
    <el-button @click="addB">b++</el-button>
  </div>
</template>

<script lang="ts" setup>
import { onMounted, onUnmounted, ref } from 'vue'
import pubsub from '../../pubsub'

interface PropsTypes {
  count: number
  addCount: () => void
}

withDefaults(defineProps<PropsTypes>(), {
  count: 0,
  addCount: () => {}
})

const a = ref<number>(6)
const b = ref<number>(10)

const addA = () => a.value++
const addB = () => b.value++

pubsub.subscribe('vue-addA', addA)
pubsub.subscribe('vue-addB', addB)

onMounted(() => {
  console.log('组件挂载了')
})
onUnmounted(() => {
  console.log('组件卸载了，清除订阅')
  pubsub.unsubscribe('vue')
})
</script>

<style scoped lang="less"></style>
