// 手写类似pubsub-js的事件队列库/vite/src/vue/components/Demo02Com.vue
<template>
  <div class="demo">
    <h2>demo02组件</h2>
    <el-button @click="addA">a++</el-button>
    <el-button @click="addB">b++</el-button>
    <demo03-com />
  </div>
</template>

<script lang="ts" setup>
import Demo03Com from './Demo03Com.vue'
import pubsub from '../../pubsub'

const addA = () => pubsub.publish('vue-addA')
const addB = () => pubsub.publish('vue-addB')
</script>

<style scoped lang="less"></style>

// 手写类似pubsub-js的事件队列库/vite/src/react/components/Demo02Com.tsx
import React, { memo } from 'react'
import { Button, Space } from 'antd'
import Demo03Com from './Demo03Com'
import pubsub from '../../pubsub'

const Demo02Com: React.FC = memo(() => {
  const addA = () => pubsub.publish('react-addA')
  const addB = () => pubsub.publish('react-addB')

  return (
    <div className="demo">
      <h2>Demo02组件</h2>
      <Space>
        <Button onClick={addA}>a++</Button>
        <Button onClick={addB}>b++</Button>
      </Space>
      <Demo03Com />
    </div>
  )
})

export default Demo02Com
