// 手写类似pubsub-js的事件队列库/src/react/App.jsx
import React, { memo, useState } from 'react'
import { Button, Space, Switch } from 'antd'
import Demo01Com from './components/Demo01Com'
import Demo02Com from './components/Demo02Com'
import pubsub from '../pubsub'

const App = memo(() => {
  const [count, setCount] = useState(0)
  const [isShow, setIsShow] = useState(true)

  const addA = () => setCount(count + 1)

  const handlePrint = () => {
    const info = pubsub.getSubscriptions('react')

    alert(info)
  }

  return (
    <div className="react-content">
      <h1>React版 - 全局组件</h1>
      <Button type="primary" onClick={() => addA()}>
        count++
      </Button>
      <h2>count: {count}</h2>
      <Space>
        是否显示子组件
        <Switch checked={isShow} onChange={setIsShow} />
      </Space>
      <Button onClick={handlePrint}>打印所有订阅以“react”开头的主题</Button>
      {isShow && (
        <div className="coms">
          <Demo01Com count={count} addCount={addA} />
          <Demo02Com />
        </div>
      )}
    </div>
  )
})

export default App

// 手写类似pubsub-js的事件队列库/src/vue/App.vue
<template>
  <div class="vue-content">
    <h1>Vue版 - 全局组件</h1>
    <el-button type="primary" @click="addCount">count++</el-button>
    <h2>count: {{ count }}</h2>
    <el-space>
      是否显示子组件
      <el-switch v-model="isShow" />
    </el-space>
    <el-button @click="handlePrint">打印所有订阅以“vue”开头的主题</el-button>
    <div class="coms" v-if="isShow">
      <demo01-com :count="count" :addCount="addCount" />
      <demo02-com />
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import Demo01Com from './components/Demo01Com'
import Demo02Com from './components/Demo02Com'
import pubsub from '../pubsub'

const count = ref(0)
const isShow = ref(true)
const addCount = () => count.value++
const handlePrint = () => {
  const info = pubsub.getSubscriptions('vue')

  alert(info)
}
</script>

<style lang="less">
.vue-content {
  background-color: pink;

  .coms {
    display: flex;
    gap: 0 20px;
    .demo {
      flex: 1;
      padding: 15px;
      border: 1px solid #000;
    }
  }
}
</style>
